### ISSUE TITLE
t?

### ISSUE THREAD

**Issue by lwy01** [bringtree/everydayCommond#71]

**Comment by bringtree** [comment]
<table>
<tr>
<td>China:</td>
<td>West:</td>
</tr>
<tr>
<td>Human nature is good but corruptible</td>
<td>Human nature is evil but perfectible</td>
</tr>
<tr>
<td>Protect people’s virtue.(美德)</td>
<td>Expect to find evil and fight against it.</td>
</tr>
<tr>
<td>Reward good behaviors</td>
<td>Punish bad behaviors.</td>
</tr>
<tr>
<td>Reward the most virtuous(有道德的) people</td>
<td>Save people from their evil nature</td>
</tr>
</table>


In India and parts of South America, （Nature dominates.） <br>
People believe the most powerful forces of life are beyond control. Whether the force is a god, fate, or magic, it cannot be overcome and must therefore be accepted.

In the West, (Humans dominate.)<br>
Christian people believe that God created the earth and all the living things in it for man. He gives Adam the right to name every living thing to have dominion over the earth.
Industrial Age: man’s unrestrained exploitation of natural resources leads to serious environmental degradation.
Now: people call for sustainable development and a harmonious relationship with nature.

In China, （Harmony）<br>
the notion of the unity of man and nature is nearly as ancient as our civilization.
Now: People are blinded by short-term profit and exploit nature excessively, causing great damage to the environment.

1. C People answer the phone by giving the name of the organization.
2. I People give cocktail parties.
3. C Intergroup rivalry is strong. //在一组,集体主义粘在一起;相对于其他群体,他们可以很有竞争力。
4. I Employee-of-the-year awards are offered.  //年度员工奖
5. C People adhere to tradition. //坚持传统
6. I People are promoted based on production and results. //人们基于生产和推广的结果。
7. I Contracts in business are used frequently. //合同在商业使用频繁。
8. I There is a need for autonomy. //有一个自治的必要性。
9. I People change jobs frequently.
10. I People believe that conflict clears the air. //集体主义不会让冲突像空气一样普遍存在
11. C There is a need for affiliation. // 集体主义联系
12. I Short-term relationships are common.
13. I It’s okay to stand out.
14. C Face saving is important.
15. I It’s common for mothers to ask their preschoolers what they want to wear today.(父母决定)
16. I Self-help books are popular.
17. C Decisions are made by consensus(共识).
18. C The language has one word for mother’s brother, another for father’s brother.
19. C Marriages are arranged.
20. C People have potluck(一起吃) dinners.


demo
```
China:Xiao Lan’s word was showings concern for the teacher who was wearing thin in the cold weather.

US:Being protected by others can be a sign of weakness or incapability.
```

Range of Values
<table>
<tr>
<td>Human nature</td>
<td>Basically good</td>
<td>Mixture of good and evil</td>
<td>Basically evil</td>
</tr>
<tr>
<td>Relations of humans to nature</td>
<td>Humans dominate</td>
<td>Harmony</td>
<td>Nature dominates</td>
</tr>
<tr>
<td>Relations b/w humans</td>
<td>Individual</td>
<td>Group oriented</td>
<td>Collateral附属</td>
</tr>
<tr>
<td>Activity orientation</td>
<td>Doing</td>
<td>Growing</td>
<td>Being</td>
</tr>
<tr>
<td>Time orientation 时间导向 </td>
<td>Future-oriented 面向未来 </td>
<td>Present-oriented</td>
<td>past-oriented</td>
</tr>
</table>



In Being culture: (People tend to:)
- protect their dignity and the dignity of others
- fulfill their role
- show the world who they are
- pay attention to people

In Doing culture: (People tend to:)
- pay attention to actions
- show the world what they can do
- try to achieve specific goals
- put emphasis to what they can achieve

In Being-in-becoming/Growing culture:
- People stress on development and growth
- People develop their potential(潜能) as a whole person
- People change and won’t be the same tomorrow as they are today.
- People pay attention to possibilities(发展潜力).


```
搬家demo
The American couple: older (old people are respected in Chinese culture), guests (guest should be treated politely and carefully )
We want to do something to be helpful, but they won’t let us.
```

```
可能用到的词汇
People are related and dependent.“We should help each other.”  cooperation, teamwork, group loyalty, and collective decision（合作、团队) Mutual(互相) aid and responsibility,Needs of the group

People are independent & self-reliant. “I can manage it myself.”personal competence and responsibility. （个人的能力和责任）Independence & Self-reliance,needs of the individual
```


In past-oriented cultures, history, established religions, and tradition are extremely important. Respect for the past is especially evident in most Asian nations because of their long and eventful histories.

Present-oriented cultures hold that the immediate moment carries the most significance.
The future is seen as ambiguous, capricious, and, in a sense, beyond the control of the individual.
Because the past is over and the future is unpredictable, present cultures, such as Filipinos and Latin Americans, enjoy living in the moment.

In future-oriented cultures, what is yet to come is most valued and the future is expected to be grander than the present or past. Change, taking chances, a stress(强调) on youth, and optimism are all hallmarks of cultures that hold this orientation.
This view toward the future is held by most Americans, who are constantly thinking about what is ahead.

<table>
<tr>
<td>Past-oriented culture</td>
<td>Present-oriented culture</td>
<td>Future-oriented culture</td>
</tr>
<tr>
<td>People value tradition.</td>
<td>People value immediate pleasure,.</td>
<td>People often have great faith in the future</td>
</tr>
<tr>
<td>People show a great deal of respect for the Old</td>
<td>People believe unseen and even unknown outside forces such as luck or fate control their lives.</td>
<td>People believe their fate is in their own hands and that they can control the results of their actions.</td>
</tr>
<tr>
<td>The parents and other elders are wise. Wisdom comes with age.</td>
<td></td>
<td>The young know what is happening.</td>
</tr>
</table>


3.1 Power Distance
Power distance is the extent to which the less powerful members of organizations and institutions accept and expect that power is distributed unequally. 权力差距指社会成员对社会或组织中的等级制度或权力分配的容忍、接受程度。

In Low/small Power Distance cultures:
People believe that everyone is by nature equal to everyone else.
There are differences in power and status in these countries, but people think they should be eliminated(根除) or minimized.
People have strong desire for establishing equality and intimacy.

In High/ large Power Distance cultures:
People think that differences in power and status is natural and important.
People accept and respect the gaps in power between people.
People accept and respect authority.
People treat others according to their position and they look to leading figures（领导人物） to know what to think and do. Children are taught to respect and obey parents, teachers, and others in authority.


In M-time culture, people:
•	Do one thing a time. (concentrate on the job)
•	Take time commitments (deadlines, schedules) seriously.
•	Stick to plans.
•	Consider time as a commodity.
•	The U.S. and Northern European cultures are M-time cultures.

In P-time culture,
•	Several things are under way at the same time. (People are highly distractible and subject to interruptions. )
•	Time is more flexible and more human-centered.
•	Relationships are more important than schedules.
•	People change plans often and easily.
•	Latin American, African, Arab and most Asian cultures are P-Time cultures.

3.2 Uncertainty Avoidance

Uncertainty avoidance indicates norms, values and beliefs related to the toleration of ambiguity.  It measures a society’s tolerance (容忍) for uncertainty（不确定） and ambiguity(含糊，不明确).

In all societies, people might feel threatened when facing uncertain and ambiguous situation. Uncertainty avoidance reflects the extent to which members of a society attempt to cope with anxiety by minimizing uncertainty. 不确定性规避是指组织或群体面对不确定性时所感受到的威胁以及试图通过制定安全规则和其他手段来避免不确定性的程度。

The uncertainty avoidance dimension expresses the degree to which a person in society feels uncomfortable with a sense of uncertainty and ambiguity.

The more uncomfortable/anxious a person feels when facing uncertainty/ambiguity, the higher uncertainty avoidance index he/she gets.

Cultures with a high uncertainty avoidance index ranking, Japan and Korea for example, seeks to establish social systems that prize rules and social expectations. Risk seems to cause them anxiety, tension and stress. People in these cultures choose to avoid conflicßts and have difficulty tolerating deviant or abnormal people and views. People tend to defer to experts and individuals in authority. Uniformity is preferred.

In cultures with a low or weak uncertainty avoidance index ranking, people enjoy less stress from ambiguity. They welcome new ideas, try new things and are more tolerant of people and views considered deviant. Singapore, Denmark, USA, India, and Great Britain are good example.
